modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/MysticMods/Glimmering/issues"
license="https://github.com/MysticMods/Glimmering/blob/master/LICENSE"
[[mods]] #mandatory
modId="glimmering" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Glimmering" #mandatory
displayURL="https://minecraft.curseforge.com/projects/glimmering"
authors="Noobanidus"
description='''
A magical Forge energy transporation system.
'''
[[dependencies.glimmering]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.glimmering]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"